#!/bin/bash
### BEGIN INIT INFO
# Provides: omxplayer
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Displays camera feeds for monitoring
# Description:
### END INIT INFO

# Camera Feeds & Positions

#First Colmn
first="screen -dmS first sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"0 0 640 360\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df92_1 --live -n -1'";
second="screen -dmS second sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"640 0 1280 360\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df94_1 --live -n -1'";
third="screen -dmS third sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"1280 0 1920 360\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df8a_2 --live -n -1'";
fourth="screen -dmS fourth sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"0 360 640 720\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df88_2 --live -n -1'";
fifth="screen -dmS fifth sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"640 360 1280 720\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df8c_2 --live -n -1 '";
sixth="screen -dmS sixth sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"1280 360 1920 720\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df8e_2 --live -n -1'";
seventh="screen -dmS seventh sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"0 720 640 1080\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df90_2 --live -n -1'";
eighth="screen -dmS eighth sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"640 720 1280 1080\" rtsp://192.168.70.8:7447/57ec2619e4b0485122ec2f61_2 --live -n -1'";
ninth="screen -dmS ninth sh -c 'omxplayer --avdict rtsp_transport:tcp --win \"1280 720 1920 1080\" rtsp://192.168.70.8:7447/56fedee59040cc51d188df90_2 --live -n -1'";



# Camera Feed Names
# (variable names from above, separated by a space)
camera_feeds=(first second third fourth fifth sixth seventh eighth ninth)

#---- There should be no need to edit anything below this line ----

# Start displaying camera feeds
case "$1" in
start)
now="$(date)"
for i in "${camera_feeds[@]}"
do
eval eval '$'$i
done
echo ""$now" - Camera Display Started"
;;

# Stop displaying camera feeds
stop)
now="$(date)"
sudo killall omxplayer.bin
echo ""$now" - Camera Display Ended"
;;

# Restart any camera feeds that have died
repair)
now="$(date)"
for i in "${camera_feeds[@]}"
do
if !(sudo screen -list | grep -q $i)
then
eval eval '$'$i
echo ""$now" -    $i is now running"
fi
done
;;

*)
echo "Usage: /etc/init.d/displaycameras {start|stop|repair}"
exit 1

;;
esac
